### ISSUE TITLE
Cannot Show Diff Info: Can't collect diff data when diff merge request

### ISSUE THREAD

**Issue by yangjuncode** [wudeyong/GitLabProjects#6]
thanks for the plugin, 
 i want to use it to review code, but have this err:

Cannot Show Diff Info: Can't collect diff data

 when click diff  in merge request list code review dialog

goland 2020.3

**Comment by wudeyong** [comment]
Which gitlab version you have using?

**Comment by yangjuncode** [comment]
gitlab ee 13.6

**Comment by yangjuncode** [comment]
we have switch to vscode for gitlab code review since there is a office gitlab plugin for it.

**Comment by wudeyong** [comment]
> we have switch to vscode for gitlab code review since there is a office gitlab plugin for it.

I just test on gitlab ce...
